/** Project Zomboid item catalog for the Give Item tool (Players page).
 *
 * Sourced directly from a user-provided export of https://pzwiki.net/wiki/PZwiki:Item_list
 * (the live Build 42 item list, saved to PZ_Items.txt at the project root and read in
 * full) - every id/name pair below was cross-checked against that file, not guessed.
 * This replaced an earlier hand-written catalog that turned out to have a number of
 * stale/incorrect ids left over from Build 41 (e.g. Base.CombatKnife, Base.Bullets223,
 * Base.SubMachineGun, Base.Boots_Combat, Base.HackSaw - none of these exist in B42;
 * B42 renamed/reworked firearms, ammo calibers, footwear, and bag naming conventions).
 *
 * Still not exhaustive - PZ_Items.txt lists thousands of entries once every color/logo/
 * camo/material variant of every cosmetic item is counted (50+ baseball cap designs,
 * dozens of near-identical leather-tanning intermediate materials, per-vehicle-class
 * spare parts, etc). Those were deliberately left out as noise for an admin give-item
 * tool. What's here favors functionally distinct, useful-to-spawn items - one or two
 * representative variants of a cosmetic item rather than all of them.
 *
 * If an item you want isn't listed here, use "Custom ID" in the picker instead of
 * browsing - the tool works with any raw item ID regardless of catalog coverage.
 * Corrections/additions: this is a plain data file, just edit the array below.
 */

export type CatalogItem = { id: string; name: string; category: string };

export const ITEM_CATEGORIES = [
  "Weapons", "Firearms", "Ammo", "Weapon Parts", "Military", "Armor", "Explosives",
  "Tools", "Medical", "Food & Drink", "Fishing", "Camping", "Materials", "Skill Books",
  "Literature", "Clothing", "Backpacks", "Miscellaneous",
] as const;

export const ITEM_CATALOG: CatalogItem[] = [
  // --- Weapons (melee) ---
  { id: "Base.Axe_Old", name: "Axe", category: "Weapons" },
  { id: "Base.Axe", name: "Firefighter Axe", category: "Weapons" },
  { id: "Base.HandAxe_Old", name: "Hand Axe", category: "Weapons" },
  { id: "Base.HandAxe", name: "Hatchet", category: "Weapons" },
  { id: "Base.BaseballBat_Nails", name: "Baseball Bat with Nails", category: "Weapons" },
  { id: "Base.BaseballBat_Spiked", name: "Baseball Bat with Spikes", category: "Weapons" },
  { id: "Base.BaseballBat_Sawblade", name: "Baseball Bat with Sawblade", category: "Weapons" },
  { id: "Base.Crowbar", name: "Crowbar", category: "Weapons" },
  { id: "Base.Machete", name: "Machete", category: "Weapons" },
  { id: "Base.Katana", name: "Katana", category: "Weapons" },
  { id: "Base.KitchenKnife", name: "Kitchen Knife", category: "Weapons" },
  { id: "Base.HuntingKnife", name: "Hunting Knife", category: "Weapons" },
  { id: "Base.HuntingKnifeForged", name: "Hunting Knife (Forged)", category: "Weapons" },
  { id: "Base.FightingKnife", name: "Fighting Knife", category: "Weapons" },
  { id: "Base.KnifeButterfly", name: "Butterfly Knife", category: "Weapons" },
  { id: "Base.SwitchKnife", name: "Switchblade", category: "Weapons" },
  { id: "Base.RailroadSpikeKnife", name: "Railroad Spike Knife", category: "Weapons" },
  { id: "Base.HandguardDagger", name: "Handguard Dagger", category: "Weapons" },
  { id: "Base.Hammer", name: "Claw Hammer", category: "Weapons" },
  { id: "Base.Sledgehammer", name: "Sledgehammer", category: "Weapons" },
  { id: "Base.Sledgehammer2", name: "Sledgehammer (Heavy)", category: "Weapons" },
  { id: "Base.MetalPipe", name: "Iron Pipe", category: "Weapons" },
  { id: "Base.LeadPipe", name: "Lead Pipe", category: "Weapons" },
  { id: "Base.Golfclub", name: "Golf Club", category: "Weapons" },
  { id: "Base.MeatCleaver", name: "Meat Cleaver", category: "Weapons" },
  { id: "Base.SpearCrafted", name: "Wooden Spear", category: "Weapons" },
  { id: "Base.SpearCraftedFireHardened", name: "Wooden Spear (Fire Hardened)", category: "Weapons" },
  { id: "Base.SpearLong", name: "Spear with Long Metal Head", category: "Weapons" },
  { id: "Base.SpearShort", name: "Spear with Metal Head", category: "Weapons" },
  { id: "Base.Pan", name: "Frying Pan", category: "Weapons" },
  { id: "Base.GardenFork", name: "Garden Fork", category: "Weapons" },
  { id: "Base.Poolcue", name: "Pool Cue", category: "Weapons" },
  { id: "Base.TennisRacket", name: "Tennis Racket", category: "Weapons" },
  { id: "Base.Gavel", name: "Gavel", category: "Weapons" },
  { id: "Base.LongMace", name: "Long Mace", category: "Weapons" },
  { id: "Base.LongSpikedClub", name: "Long Spiked Club", category: "Weapons" },
  { id: "Base.LongMace_Stone", name: "Long Stone Mace", category: "Weapons" },
  { id: "Base.Mace", name: "Mace", category: "Weapons" },
  { id: "Base.Mace_Stone", name: "Stone Mace", category: "Weapons" },
  { id: "Base.Nightstick", name: "Nightstick", category: "Weapons" },
  { id: "Base.ShortBat", name: "Short Bat", category: "Weapons" },
  { id: "Base.SpikedShortBat", name: "Short Bat with Spikes", category: "Weapons" },
  { id: "Base.ShortSword", name: "Shortsword", category: "Weapons" },
  { id: "Base.CrudeShortSword", name: "Simple Shortsword", category: "Weapons" },
  { id: "Base.CrudeSword", name: "Simple Sword", category: "Weapons" },
  { id: "Base.Sword", name: "Sword", category: "Weapons" },
  { id: "Base.Scythe", name: "Scythe", category: "Weapons" },
  // -- crafted/improvised (curated subset - many more exist for on-the-fly crafting) --
  { id: "Base.AxeStone", name: "Crude Stone Axe", category: "Weapons" },
  { id: "Base.StoneAxeLarge", name: "Large Stone Axe", category: "Weapons" },
  { id: "Base.CrudeKnife", name: "Simple Metal Knife", category: "Weapons" },
  { id: "Base.LongCrudeKnife", name: "Long Simple Metal Knife", category: "Weapons" },
  { id: "Base.FlintKnife", name: "Stone Knife", category: "Weapons" },
  { id: "Base.GlassShiv", name: "Glass Shiv", category: "Weapons" },
  { id: "Base.KnifeShiv", name: "Shiv", category: "Weapons" },
  { id: "Base.Machete_Crude", name: "Scrap Metal Chopper", category: "Weapons" },
  { id: "Base.Sword_Scrap", name: "Scrap Metal Sword", category: "Weapons" },
  { id: "Base.Morningstar_Scrap", name: "Scrap Metal Morningstar", category: "Weapons" },
  { id: "Base.ScrapMaul", name: "Scrap Metal Maul", category: "Weapons" },
  { id: "Base.StoneMaul", name: "Stone Maul", category: "Weapons" },
  { id: "Base.Cudgel_Spike", name: "Cudgel with Spikes", category: "Weapons" },
  { id: "Base.Cudgel_Nails", name: "Cudgel with Nails", category: "Weapons" },
  { id: "Base.TreeBranch_Nails", name: "Tree Branch with Nails", category: "Weapons" },
  { id: "Base.WoodenStick_Nails", name: "Wooden Rod with Nails", category: "Weapons" },
  { id: "Base.SpearHuntingKnife", name: "Spear with Hunting Knife", category: "Weapons" },
  { id: "Base.SpearKnife", name: "Spear with Kitchen Knife", category: "Weapons" },
  { id: "Base.SpearStone", name: "Spear with Stone Head", category: "Weapons" },
  { id: "Base.JawboneBovide_Axe", name: "Jawbone War Axe", category: "Weapons" },
  { id: "Base.BoneClub", name: "Bone Club", category: "Weapons" },
  { id: "Base.LargeBoneClub_Spiked", name: "Sturdy Bone Club with Spikes", category: "Weapons" },
  { id: "Base.SmashedBottle", name: "Smashed Bottle", category: "Weapons" },

  // --- Firearms ---
  { id: "Base.Pistol", name: "M9 Pistol", category: "Firearms" },
  { id: "Base.Pistol2", name: "M1911 Pistol", category: "Firearms" },
  { id: "Base.Pistol3", name: "B-F Pistol", category: "Firearms" },
  { id: "Base.Revolver", name: "Patrol Revolver", category: "Firearms" },
  { id: "Base.Revolver_Short", name: "SN38 Revolver", category: "Firearms" },
  { id: "Base.Revolver_Long", name: "Magnum", category: "Firearms" },
  { id: "Base.Shotgun", name: "JS-2000 Shotgun", category: "Firearms" },
  { id: "Base.ShotgunSawnoff", name: "Sawed-off JS-2000 Shotgun", category: "Firearms" },
  { id: "Base.DoubleBarrelShotgun", name: "Double Barrel Shotgun", category: "Firearms" },
  { id: "Base.DoubleBarrelShotgunSawnoff", name: "Sawed-off Double Barrel Shotgun", category: "Firearms" },
  { id: "Base.JS3T_Shotgun", name: "JS-3T Tactical Shotgun", category: "Firearms" },
  { id: "Base.VarmintRifle", name: "MSR700 Rifle", category: "Firearms" },
  { id: "Base.HuntingRifle", name: "MSR788 Rifle", category: "Firearms" },
  { id: "Base.MSR7T_Rifle", name: "MSR7T Tactical Rifle", category: "Firearms" },
  { id: "Base.AssaultRifle", name: "M16 Assault Rifle", category: "Firearms" },
  { id: "Base.AssaultRifle2", name: "M1A Rifle", category: "Firearms" },
  { id: "Base.L92_Carbine", name: "L92 Carbine", category: "Firearms" },
  { id: "Base.L94_Rifle", name: "L94 Rifle", category: "Firearms" },
  { id: "Base.JS14_Rifle", name: "JS-14 Rifle", category: "Firearms" },
  { id: "Base.TrapperCarbine", name: "Trapper Carbine", category: "Firearms" },
  { id: "Base.FlareGun", name: "Flare Gun", category: "Firearms" },

  // --- Ammo ---
  { id: "Base.Bullets9mm", name: "9x19mm Round", category: "Ammo" },
  { id: "Base.Bullets9mmBox", name: "Box of 9x19mm Rounds", category: "Ammo" },
  { id: "Base.Bullets9mmCarton", name: "Carton of 9x19mm Rounds", category: "Ammo" },
  { id: "Base.Bullets38", name: ".38 Special Round", category: "Ammo" },
  { id: "Base.Bullets38Box", name: "Box of .38 Special Rounds", category: "Ammo" },
  { id: "Base.Bullets38Carton", name: "Carton of .38 Special Rounds", category: "Ammo" },
  { id: "Base.Bullets44", name: ".44 Magnum Round", category: "Ammo" },
  { id: "Base.Bullets44Box", name: "Box of .44 Magnum Rounds", category: "Ammo" },
  { id: "Base.Bullets44Carton", name: "Carton of .44 Magnum Rounds", category: "Ammo" },
  { id: "Base.Bullets45", name: ".45 ACP Round", category: "Ammo" },
  { id: "Base.Bullets45Box", name: "Box of .45 ACP Rounds", category: "Ammo" },
  { id: "Base.Bullets45Carton", name: "Carton of .45 ACP Rounds", category: "Ammo" },
  { id: "Base.Bullets357", name: ".357 Magnum Round", category: "Ammo" },
  { id: "Base.Bullets357Box", name: "Box of .357 Magnum Rounds", category: "Ammo" },
  { id: "Base.Bullets357Carton", name: "Carton of .357 Magnum Rounds", category: "Ammo" },
  { id: "Base.3030Bullets", name: ".30-30 Round", category: "Ammo" },
  { id: "Base.3030Box", name: "Box of .30-30 Rounds", category: "Ammo" },
  { id: "Base.3030Carton", name: "Carton of .30-30 Rounds", category: "Ammo" },
  { id: "Base.556Bullets", name: "5.56x45mm Round", category: "Ammo" },
  { id: "Base.556Box", name: "Box of 5.56x45mm Rounds", category: "Ammo" },
  { id: "Base.556Carton", name: "Carton of 5.56x45mm Rounds", category: "Ammo" },
  { id: "Base.308Bullets", name: "7.62x51mm Round", category: "Ammo" },
  { id: "Base.308Box", name: "Box of 7.62x51mm Rounds", category: "Ammo" },
  { id: "Base.308Carton", name: "Carton of 7.62x51mm Rounds", category: "Ammo" },
  { id: "Base.ShotgunShells", name: "12g Round", category: "Ammo" },
  { id: "Base.ShotgunShellsBox", name: "Box of 12g Rounds", category: "Ammo" },
  { id: "Base.ShotgunShellsCarton", name: "Carton of 12g Rounds", category: "Ammo" },
  { id: "Base.9mmClip", name: "M9 Magazine", category: "Ammo" },
  { id: "Base.45Clip", name: "M1911 Auto Magazine", category: "Ammo" },
  { id: "Base.44Clip", name: "B-F Magazine", category: "Ammo" },
  { id: "Base.556Clip", name: "M16 Magazine", category: "Ammo" },
  { id: "Base.M14Clip", name: "M1A Magazine", category: "Ammo" },
  { id: "Base.JS14_Clip", name: "JS-14 Magazine", category: "Ammo" },
  { id: "Base.FlareGunShell", name: "Flare", category: "Ammo" },

  // --- Weapon Parts (attachments) ---
  { id: "Base.x2Scope", name: "x2 Scope", category: "Weapon Parts" },
  { id: "Base.x4Scope", name: "x4 Scope", category: "Weapon Parts" },
  { id: "Base.x8Scope", name: "x8 Scope", category: "Weapon Parts" },
  { id: "Base.RedDot", name: "Red Dot Sight", category: "Weapon Parts" },
  { id: "Base.Laser", name: "Laser Sight", category: "Weapon Parts" },
  { id: "Base.TritiumSights", name: "Tritium Pistol Sights", category: "Weapon Parts" },
  { id: "Base.GunLight", name: "Gun Light", category: "Weapon Parts" },
  { id: "Base.RecoilPad", name: "Recoil Pad", category: "Weapon Parts" },
  { id: "Base.ChokeTubeFull", name: "Choke Tube - Full", category: "Weapon Parts" },
  { id: "Base.ChokeTubeImproved", name: "Choke Tube - Improved", category: "Weapon Parts" },
  { id: "Base.AmmoStraps", name: "Ammo Straps", category: "Weapon Parts" },

  // --- Military ---
  { id: "Base.Jacket_ArmyCamoDesert", name: "Military Jacket - Desert Camo", category: "Military" },
  { id: "Base.Jacket_ArmyCamoGreen", name: "Military Jacket - Green Camo", category: "Military" },
  { id: "Base.Jacket_ArmyOliveDrab", name: "Military Jacket - Olive Drab", category: "Military" },
  { id: "Base.Jacket_ArmyCamoTigerStripe", name: "Military Jacket - Tiger Stripe Camo", category: "Military" },
  { id: "Base.Jacket_ArmyCamoUrban", name: "Military Jacket - Urban Camo", category: "Military" },
  { id: "Base.Jacket_ArmyCamoMilius", name: "Military Jacket - Foreign Camo", category: "Military" },
  { id: "Base.Jacket_CoatArmy", name: "Military Jacket - Officer", category: "Military" },
  { id: "Base.Trousers_ArmyService", name: "Military Pants", category: "Military" },
  { id: "Base.Trousers_CamoDesert", name: "Military Pants - Desert Camo", category: "Military" },
  { id: "Base.Trousers_CamoGreen", name: "Military Pants - Green Camo", category: "Military" },
  { id: "Base.Trousers_OliveDrab", name: "Military Pants - Olive Drab", category: "Military" },
  { id: "Base.Trousers_CamoTigerStripe", name: "Military Pants - Tiger Stripe Camo", category: "Military" },
  { id: "Base.Trousers_CamoUrban", name: "Military Pants - Urban Camo", category: "Military" },
  { id: "Base.Shirt_CamoDesert", name: "Military Shirt - Desert Camo", category: "Military" },
  { id: "Base.Shirt_CamoGreen", name: "Military Shirt - Green Camo", category: "Military" },
  { id: "Base.Shirt_OliveDrab", name: "Military Shirt - Olive Drab", category: "Military" },
  { id: "Base.Tshirt_ArmyGreen", name: "Military T-shirt", category: "Military" },
  { id: "Base.Tshirt_CamoDesert", name: "Military T-shirt - Desert Camo", category: "Military" },
  { id: "Base.Tshirt_OliveDrab", name: "Military T-shirt - Olive Drab", category: "Military" },
  { id: "Base.Shoes_ArmyBoots", name: "Military Boots", category: "Military" },
  { id: "Base.Shoes_ArmyBootsDesert", name: "Military Boots - Desert", category: "Military" },
  { id: "Base.Hat_BeretArmy", name: "Army Beret", category: "Military" },
  { id: "Base.Hat_PeakedCapArmy", name: "Peaked Military Cap", category: "Military" },
  { id: "Base.Hat_BaseballCapArmy", name: "Baseball Cap - Army", category: "Military" },
  { id: "Base.Ghillie_Top", name: "Ghillie Suit - Torso", category: "Military" },
  { id: "Base.Ghillie_Trousers", name: "Ghillie Suit - Pants", category: "Military" },
  { id: "Base.Bag_ALICEpack", name: "Military Backpack (ALICE)", category: "Military" },
  { id: "Base.Bag_ALICEpack_Army", name: "Military Backpack (ALICE, Army)", category: "Military" },
  { id: "Base.Bag_ALICEpack_DesertCamo", name: "Military Backpack (ALICE, Desert)", category: "Military" },
  { id: "Base.Bag_SurvivorBag", name: "Military Backpack (Survivor)", category: "Military" },
  { id: "Base.Bag_Military", name: "Duffel Bag (Military)", category: "Military" },
  { id: "Base.Bag_ChestRig", name: "Chest Rig", category: "Military" },
  { id: "Base.Bag_AmmoBox_Mixed", name: "Ammunition Box", category: "Military" },
  { id: "Base.CanteenMilitary", name: "Canteen (Military)", category: "Military" },
  { id: "Base.DogTags", name: "Dog Tags", category: "Military" },
  { id: "Base.ManPackRadio", name: "US ARMY COMM. Manpack Radio", category: "Military" },
  { id: "Base.HamRadio2", name: "US ARMY COMM. Ham Radio", category: "Military" },
  { id: "Base.WalkieTalkie5", name: "US Army Walkie Talkie", category: "Military" },
  { id: "Base.WalkieTalkie4", name: "Tactical Walkie Talkie", category: "Military" },
  { id: "Base.Binoculars", name: "Binoculars", category: "Military" },

  // --- Armor / Protective Gear ---
  { id: "Base.Hat_Army", name: "Military Helmet", category: "Armor" },
  { id: "Base.Hat_ArmyDesert", name: "Military Helmet - Desert", category: "Armor" },
  { id: "Base.Hat_SWAT", name: "SWAT Helmet", category: "Armor" },
  { id: "Base.Hat_RiotHelmet", name: "Riot Helmet", category: "Armor" },
  { id: "Base.Hat_SPHhelmet", name: "Air Force Pilot Helmet", category: "Armor" },
  { id: "Base.Hat_GasMask", name: "Gas Mask", category: "Armor" },
  { id: "Base.Hat_NBCmask", name: "Nuclear Biochemical Mask", category: "Armor" },
  { id: "Base.Hat_HardHat", name: "Hard Hat", category: "Armor" },
  { id: "Base.Hat_CrashHelmetFULL", name: "Crash Helmet (Motorcycle)", category: "Armor" },
  { id: "Base.Hat_MetalHelmet", name: "Crude Metal Helmet", category: "Armor" },
  { id: "Base.Hat_MetalScrapHelmet", name: "Scrap Metal Helmet", category: "Armor" },
  { id: "Base.Vest_BulletCivilian", name: "Bulletproof Vest - Civilian", category: "Armor" },
  { id: "Base.Vest_BulletArmy", name: "Bulletproof Vest - Military", category: "Armor" },
  { id: "Base.Vest_BulletDesert", name: "Bulletproof Vest - Military (Desert)", category: "Armor" },
  { id: "Base.Vest_BulletPolice", name: "Bulletproof Vest - Police", category: "Armor" },
  { id: "Base.Vest_BulletSWAT", name: "Bulletproof Vest - SWAT", category: "Armor" },
  { id: "Base.Cuirass_Metal", name: "Metal Body Armor", category: "Armor" },
  { id: "Base.Cuirass_MetalScrap", name: "Scrap Metal Body Armor", category: "Armor" },
  { id: "Base.Cuirass_Bone", name: "Bone Body Armor", category: "Armor" },
  { id: "Base.Cuirass_Wood", name: "Wooden Body Armor", category: "Armor" },
  { id: "Base.Vambrace_Right", name: "Metal Forearm Armor - Right", category: "Armor" },
  { id: "Base.Vambrace_Left", name: "Metal Forearm Armor - Left", category: "Armor" },
  { id: "Base.Greave_Right", name: "Metal Shin Armor - Right", category: "Armor" },
  { id: "Base.Greave_Left", name: "Metal Shin Armor - Left", category: "Armor" },
  { id: "Base.Shoulderpad_Metal_L", name: "Metal Shoulder Armor - Left", category: "Armor" },
  { id: "Base.Shoulderpad_Metal_R", name: "Metal Shoulder Armor - Right", category: "Armor" },
  { id: "Base.ElbowPad_Right", name: "Elbow Pad - Right", category: "Armor" },
  { id: "Base.ElbowPad_Left", name: "Elbow Pad - Left", category: "Armor" },
  { id: "Base.Kneepad_Right", name: "Kneepad - Right", category: "Armor" },
  { id: "Base.Kneepad_Left", name: "Kneepad - Left", category: "Armor" },
  { id: "Base.ShinKneeGuard_L", name: "Shin Guard - Left", category: "Armor" },
  { id: "Base.ShinKneeGuard_R", name: "Shin Guard - Right", category: "Armor" },
  { id: "Base.Gaiter_Left", name: "Gaiter - Left", category: "Armor" },
  { id: "Base.Gaiter_Right", name: "Gaiter - Right", category: "Armor" },
  { id: "Base.SCBA", name: "SCBA (Self-Contained Breathing Apparatus)", category: "Armor" },
  { id: "Base.Hat_DustMask", name: "Dust Mask", category: "Armor" },
  { id: "Base.Hat_BuildersRespirator", name: "Half Mask Respirator", category: "Armor" },
  { id: "Base.AthleticCup", name: "Athletic Cup", category: "Armor" },

  // --- Explosives ---
  { id: "Base.Molotov", name: "Molotov Cocktail", category: "Explosives" },
  { id: "Base.PipeBomb", name: "Pipe Bomb", category: "Explosives" },
  { id: "Base.PipeBombTriggered", name: "Pipe Bomb with Timer", category: "Explosives" },
  { id: "Base.SmokeBomb", name: "Smoke Bomb", category: "Explosives" },
  { id: "Base.NoiseTrap", name: "Noise Maker", category: "Explosives" },
  { id: "Base.Aerosolbomb", name: "Aerosol Bomb", category: "Explosives" },
  { id: "Base.FlameTrap", name: "Fire Bomb", category: "Explosives" },
  { id: "Base.Firecracker", name: "Firecrackers", category: "Explosives" },
  { id: "Base.Firecracker_Crafted", name: "Firecracker - Crafted", category: "Explosives" },

  // --- Tools ---
  { id: "Base.Screwdriver", name: "Screwdriver", category: "Tools" },
  { id: "Base.Saw", name: "Hacksaw", category: "Tools" },
  { id: "Base.SmallSaw", name: "Small Hacksaw", category: "Tools" },
  { id: "Base.GardenSaw", name: "Wood Saw", category: "Tools" },
  { id: "Base.Wrench", name: "Wrench", category: "Tools" },
  { id: "Base.Ratchet", name: "Ratchet Wrench", category: "Tools" },
  { id: "Base.PipeWrench", name: "Pipe Wrench", category: "Tools" },
  { id: "Base.Pliers", name: "Pliers", category: "Tools" },
  { id: "Base.MetalworkingPliers", name: "Metalworking Pliers", category: "Tools" },
  { id: "Base.ViseGrips", name: "Vise Grips", category: "Tools" },
  { id: "Base.Shovel2", name: "Shovel", category: "Tools" },
  { id: "Base.Shovel", name: "Spade", category: "Tools" },
  { id: "Base.SnowShovel", name: "Snow Shovel", category: "Tools" },
  { id: "Base.MasonsTrowel", name: "Mason's Trowel", category: "Tools" },
  { id: "Base.HandShovel", name: "Gardening Trowel", category: "Tools" },
  { id: "Base.SewingKit", name: "Sewing Kit", category: "Tools" },
  { id: "Base.Needle", name: "Needle", category: "Tools" },
  { id: "Base.Lighter", name: "Lighter", category: "Tools" },
  { id: "Base.LighterDisposable", name: "Lighter - Disposable", category: "Tools" },
  { id: "Base.Matchbox", name: "Box of Matches", category: "Tools" },
  { id: "Base.Matches", name: "Matchbook", category: "Tools" },
  { id: "Base.Rope", name: "Rope", category: "Tools" },
  { id: "Base.DuctTape", name: "Duct Tape", category: "Tools" },
  { id: "Base.BlowTorch", name: "Welding Torch", category: "Tools" },
  { id: "Base.WeldingMask", name: "Welding Mask", category: "Tools" },
  { id: "Base.PropaneTank", name: "Propane Tank", category: "Tools" },
  { id: "Base.HandTorch", name: "Flashlight", category: "Tools" },
  { id: "Base.Torch", name: "Flashlight - Heavy Duty", category: "Tools" },
  { id: "Base.WalkieTalkie1", name: "Walkie Talkie", category: "Tools" },
  { id: "Base.WalkieTalkie3", name: "Premium Tech. Walkie Talkie", category: "Tools" },
  { id: "Base.Battery", name: "Battery", category: "Tools" },
  { id: "Base.BatteryBox", name: "Box of Batteries", category: "Tools" },
  { id: "Base.Multitool", name: "Multitool", category: "Tools" },
  { id: "Base.BoltCutters", name: "Bolt Cutters", category: "Tools" },
  { id: "Base.CompassDirectional", name: "Compass", category: "Tools" },
  { id: "Base.MeasuringTape", name: "Measuring Tape", category: "Tools" },
  { id: "Base.Zipties", name: "Zip Ties", category: "Tools" },
  { id: "Base.Key_Blank", name: "Blank Key", category: "Tools" },
  { id: "Base.CombinationPadlock", name: "Combination Padlock", category: "Tools" },
  { id: "Base.Padlock", name: "Padlock", category: "Tools" },
  { id: "Base.KeyPadlock", name: "Padlock Key", category: "Tools" },

  // --- Medical ---
  { id: "Base.Bandage", name: "Bandage", category: "Medical" },
  { id: "Base.Bandaid", name: "Bandage - Adhesive", category: "Medical" },
  { id: "Base.AlcoholWipes", name: "Alcohol Wipes", category: "Medical" },
  { id: "Base.Disinfectant", name: "Bottle of Disinfectant", category: "Medical" },
  { id: "Base.Antibiotics", name: "Antibiotics", category: "Medical" },
  { id: "Base.AntibioticsBox", name: "Box of Antibiotics", category: "Medical" },
  { id: "Base.Pills", name: "Painkillers", category: "Medical" },
  { id: "Base.PillsBeta", name: "Beta Blockers", category: "Medical" },
  { id: "Base.PillsSleepingTablets", name: "Sleeping Pills", category: "Medical" },
  { id: "Base.PillsAntiDep", name: "Antidepressants", category: "Medical" },
  { id: "Base.PillsVitamins", name: "Caffeine Pills", category: "Medical" },
  { id: "Base.SutureNeedle", name: "Suture Needle", category: "Medical" },
  { id: "Base.SutureNeedleBox", name: "Box of Suture Needles", category: "Medical" },
  { id: "Base.Thread", name: "Thread", category: "Medical" },
  { id: "Base.Splint", name: "Splint", category: "Medical" },
  { id: "Base.ColdPack", name: "Cold Pack", category: "Medical" },
  { id: "Base.CottonBalls", name: "Cotton Balls", category: "Medical" },
  { id: "Base.Scalpel", name: "Scalpel", category: "Medical" },
  { id: "Base.Stethoscope", name: "Stethoscope", category: "Medical" },
  { id: "Base.Tweezers", name: "Tweezers", category: "Medical" },
  { id: "Base.ScissorsBluntMedical", name: "Medical Shears", category: "Medical" },
  { id: "Base.Gloves_Surgical", name: "Surgical Gloves", category: "Medical" },
  { id: "Base.Hat_SurgicalMask", name: "Surgical Mask", category: "Medical" },
  { id: "Base.FirstAidKit", name: "First Aid Kit", category: "Medical" },
  { id: "Base.FirstAidKit_Military", name: "First Aid Kit - Military", category: "Medical" },

  // --- Food & Drink ---
  { id: "Base.WaterBottle", name: "Water Bottle", category: "Food & Drink" },
  { id: "Base.BeerBottle", name: "Beer", category: "Food & Drink" },
  { id: "Base.Whiskey", name: "Whiskey", category: "Food & Drink" },
  { id: "Base.Wine", name: "White Wine", category: "Food & Drink" },
  { id: "Base.TinnedBeans", name: "Canned Beans", category: "Food & Drink" },
  { id: "Base.CannedCorn", name: "Canned Corn", category: "Food & Drink" },
  { id: "Base.CannedPeas", name: "Canned Peas", category: "Food & Drink" },
  { id: "Base.TinnedSoup", name: "Canned Vegetable Soup", category: "Food & Drink" },
  { id: "Base.CannedMushroomSoup", name: "Canned Mushroom Soup", category: "Food & Drink" },
  { id: "Base.Crisps", name: "Chips - Plain", category: "Food & Drink" },
  { id: "Base.Rice", name: "Rice", category: "Food & Drink" },
  { id: "Base.Apple", name: "Apple", category: "Food & Drink" },
  { id: "Base.Banana", name: "Banana", category: "Food & Drink" },
  { id: "Base.Crackers", name: "Crackers", category: "Food & Drink" },
  { id: "Base.PeanutButter", name: "Peanut Butter", category: "Food & Drink" },

  // --- Fishing ---
  { id: "Base.FishingRod", name: "Fishing Rod", category: "Fishing" },
  { id: "Base.CraftedFishingRod", name: "Makeshift Fishing Rod", category: "Fishing" },
  { id: "Base.Gaffhook", name: "Gaff Hook", category: "Fishing" },
  { id: "Base.FishingNet", name: "Fishing Net", category: "Fishing" },
  { id: "Base.FishingHook", name: "Fishing Hook", category: "Fishing" },
  { id: "Base.FishingHook_Forged", name: "Forged Fishing Hook", category: "Fishing" },
  { id: "Base.FishingLine", name: "Fishing Line", category: "Fishing" },
  { id: "Base.PremiumFishingLine", name: "Premium Fishing Line", category: "Fishing" },
  { id: "Base.Bobber", name: "Bobber", category: "Fishing" },
  { id: "Base.Worm", name: "Worm", category: "Fishing" },
  { id: "Base.Chum", name: "Chum", category: "Fishing" },
  { id: "Base.JigLure", name: "Jig Lure", category: "Fishing" },
  { id: "Base.MinnowLure", name: "Minnow Lure", category: "Fishing" },
  { id: "Base.Tacklebox", name: "Tacklebox", category: "Fishing" },

  // --- Camping ---
  { id: "Base.TentGreen", name: "Tent", category: "Camping" },
  { id: "Base.TentGreen_Packed", name: "Tent (Packed)", category: "Camping" },
  { id: "Base.HideTent", name: "Hide Tent", category: "Camping" },
  { id: "Base.ImprovisedTentKit", name: "Improvised Tent Kit", category: "Camping" },
  { id: "Base.SleepingBag_Green", name: "Sleeping Bag", category: "Camping" },
  { id: "Base.SleepingBag_Green_Packed", name: "Sleeping Bag (Packed)", category: "Camping" },
  { id: "Base.SleepingBag_HighQuality_Brown", name: "High Quality Sleeping Bag", category: "Camping" },
  { id: "Base.SleepingBag_Hide", name: "Hide Sleeping Bag", category: "Camping" },
  { id: "Base.DryFirestarterBlock", name: "Firestarting Block", category: "Camping" },
  { id: "Base.MagnesiumFirestarter", name: "Magnesium Firestarter", category: "Camping" },
  { id: "Base.InsectRepellent", name: "Insect Repellent", category: "Camping" },
  { id: "Base.WaterPurificationTablets", name: "Water Purification Tablets", category: "Camping" },
  { id: "Base.Cooler", name: "Cooler", category: "Camping" },
  { id: "Base.Spork", name: "Plastic Spork", category: "Camping" },

  // --- Materials ---
  { id: "Base.Nails", name: "Nails", category: "Materials" },
  { id: "Base.NailsBox", name: "Box of Nails", category: "Materials" },
  { id: "Base.Plank", name: "Plank", category: "Materials" },
  { id: "Base.Sheet", name: "Sheet", category: "Materials" },
  { id: "Base.SheetRope", name: "Sheet Rope", category: "Materials" },
  { id: "Base.ScrapMetal", name: "Scrap Metal", category: "Materials" },
  { id: "Base.SheetMetal", name: "Steel Sheet", category: "Materials" },
  { id: "Base.Log", name: "Log", category: "Materials" },
  { id: "Base.Twine", name: "Twine", category: "Materials" },
  { id: "Base.Bleach", name: "Bleach Bottle", category: "Materials" },
  { id: "Base.RippedSheets", name: "Rag", category: "Materials" },
  { id: "Base.ElectronicsScrap", name: "Scrap Electronics", category: "Materials" },
  { id: "Base.Wire", name: "Wire", category: "Materials" },
  { id: "Base.PetrolCan", name: "Gas Can", category: "Materials" },
  { id: "Base.GunPowder", name: "Gunpowder", category: "Materials" },
  { id: "Base.Charcoal", name: "Charcoal", category: "Materials" },
  { id: "Base.BarbedWire", name: "Barbed Wire", category: "Materials" },
  { id: "Base.String", name: "String", category: "Materials" },
  { id: "Base.LeatherStrips", name: "Leather Strips", category: "Materials" },
  { id: "Base.Screws", name: "Screws", category: "Materials" },
  { id: "Base.SteelIngot", name: "Steel Ingot", category: "Materials" },
  { id: "Base.IronIngot", name: "Iron Ingot", category: "Materials" },
  { id: "Base.WeldingRods", name: "Welding Rods", category: "Materials" },

  // --- Skill Books ---
  { id: "Base.BookAimingSet", name: "Set of Aiming Books", category: "Skill Books" },
  { id: "Base.BookHusbandrySet", name: "Set of Animal Care Books", category: "Skill Books" },
  { id: "Base.BookBlacksmithSet", name: "Set of Blacksmithing Books", category: "Skill Books" },
  { id: "Base.BookButcheringSet", name: "Set of Butchering Books", category: "Skill Books" },
  { id: "Base.BookCarpentrySet", name: "Set of Carpentry Books", category: "Skill Books" },
  { id: "Base.BookCarvingSet", name: "Set of Carving Books", category: "Skill Books" },
  { id: "Base.BookCookingSet", name: "Set of Cooking Books", category: "Skill Books" },
  { id: "Base.BookElectricianSet", name: "Set of Electrical Books", category: "Skill Books" },
  { id: "Base.BookFarmingSet", name: "Set of Farming Books", category: "Skill Books" },
  { id: "Base.BookFirstAidSet", name: "Set of First Aid Books", category: "Skill Books" },
  { id: "Base.BookFishingSet", name: "Set of Fishing Books", category: "Skill Books" },
  { id: "Base.BookForagingSet", name: "Set of Foraging Books", category: "Skill Books" },
  { id: "Base.BookGlassmakingSet", name: "Set of Glassmaking Books", category: "Skill Books" },
  { id: "Base.BookFlintKnappingSet", name: "Set of Knapping Books", category: "Skill Books" },
  { id: "Base.BookLongBladeSet", name: "Set of Long Blade Books", category: "Skill Books" },
  { id: "Base.BookMaintenanceSet", name: "Set of Maintenance Books", category: "Skill Books" },
  { id: "Base.BookMasonrySet", name: "Set of Masonry Books", category: "Skill Books" },
  { id: "Base.BookMechanicsSet", name: "Set of Mechanics Books", category: "Skill Books" },
  { id: "Base.BookPotterySet", name: "Set of Pottery Books", category: "Skill Books" },
  { id: "Base.BookReloadingSet", name: "Set of Reloading Books", category: "Skill Books" },
  { id: "Base.BookTailoringSet", name: "Set of Tailoring Books", category: "Skill Books" },
  { id: "Base.BookTrackingSet", name: "Set of Tracking Books", category: "Skill Books" },
  { id: "Base.BookTrappingSet", name: "Set of Trapping Books", category: "Skill Books" },
  { id: "Base.BookMetalWeldingSet", name: "Set of Welding Books", category: "Skill Books" },
  // -- individual tier I & V (a taste of the low/high end of each series) --
  { id: "Base.BookAiming1", name: 'Aiming I: "Better Aiming"', category: "Skill Books" },
  { id: "Base.BookAiming5", name: 'Aiming V: "Secrets From the World\'s Best Snipers"', category: "Skill Books" },
  { id: "Base.BookFirstAid1", name: 'First Aid I: "A Scouts Injury Guide"', category: "Skill Books" },
  { id: "Base.BookFirstAid5", name: 'First Aid V: "Surgical Techniques of the Operating Room"', category: "Skill Books" },
  { id: "Base.BookCarpentry1", name: 'Carpentry I: "A Guide to Nailing"', category: "Skill Books" },
  { id: "Base.BookCarpentry5", name: 'Carpentry V: "Site Joinery and Architectural Carpentry"', category: "Skill Books" },
  { id: "Base.BookCooking1", name: 'Cooking I: "Better Burger Flipping"', category: "Skill Books" },
  { id: "Base.BookCooking5", name: 'Cooking V: "Ruban Vert Gourmet - Complete Cooking Techniques"', category: "Skill Books" },
  { id: "Base.BookElectrician1", name: 'Electrical I: "Basic Electronics"', category: "Skill Books" },
  { id: "Base.BookElectrician5", name: 'Electrical V: "Understanding Integrated Controls for Electronic Systems"', category: "Skill Books" },
  { id: "Base.BookMechanic1", name: 'Mechanics I: "Carzone\'s Repair Guide"', category: "Skill Books" },
  { id: "Base.BookMechanic5", name: 'Mechanics V: "Mastering Automotive Fault Diagnosis Techniques"', category: "Skill Books" },
  { id: "Base.BookFarming1", name: 'Agriculture I: "Better Gardening"', category: "Skill Books" },
  { id: "Base.BookFarming5", name: 'Agriculture V: "USDA Guide to Agricultural Output Maximization"', category: "Skill Books" },

  // --- Literature ---
  { id: "Base.Book", name: "Book", category: "Literature" },
  { id: "Base.Book_Bible", name: "Book: The Bible", category: "Literature" },
  { id: "Base.Newspaper_New", name: "Newspaper", category: "Literature" },
  { id: "Base.Magazine_New", name: "Magazine", category: "Literature" },
  { id: "Base.Magazine_Firearm_New", name: "Magazine (firearm)", category: "Literature" },
  { id: "Base.Magazine_Military_New", name: "Magazine (military)", category: "Literature" },
  { id: "Base.ComicBook", name: "Comic Book", category: "Literature" },
  { id: "Base.Map", name: "Map", category: "Literature" },
  { id: "Base.TVMagazine", name: "Magazine: TV Monthly", category: "Literature" },
  { id: "Base.Notebook", name: "Notebook", category: "Literature" },
  { id: "Base.Diary1", name: "Diary", category: "Literature" },
  { id: "Base.Paperback", name: "Paperback", category: "Literature" },

  // --- Clothing ---
  { id: "Base.Tshirt_DefaultTEXTURE", name: "T-shirt", category: "Clothing" },
  { id: "Base.Trousers", name: "Pants", category: "Clothing" },
  { id: "Base.Shoes_Black", name: "Shoes", category: "Clothing" },
  { id: "Base.Shoes_BlackBoots", name: "Boots", category: "Clothing" },
  { id: "Base.Shoes_HikingBoots", name: "Hiking Boots", category: "Clothing" },
  { id: "Base.Shoes_Wellies", name: "Rubber Boots", category: "Clothing" },
  { id: "Base.Shoes_CowboyBoots", name: "Western Boots", category: "Clothing" },
  { id: "Base.Shoes_WorkBoots", name: "Work Boots", category: "Clothing" },
  { id: "Base.Hat_WinterHat", name: "Winter Hat", category: "Clothing" },
  { id: "Base.Hat_Beany", name: "Beanie", category: "Clothing" },
  { id: "Base.Hat_BaseballCap", name: "Baseball Cap", category: "Clothing" },
  { id: "Base.Gloves_LeatherGloves", name: "Leather Gloves", category: "Clothing" },
  { id: "Base.Jacket_WhiteTINT", name: "Jacket", category: "Clothing" },
  { id: "Base.HoodieUP_WhiteTINT", name: "Hoodie", category: "Clothing" },
  { id: "Base.Jumper_RoundNeck", name: "Sweater - Round Neck", category: "Clothing" },
  { id: "Base.Vest_HighViz", name: "High Visibility Vest", category: "Clothing" },
  { id: "Base.HazmatSuit", name: "Hazmat Suit", category: "Clothing" },

  // --- Backpacks ---
  { id: "Base.Bag_Schoolbag", name: "Small Backpack", category: "Backpacks" },
  { id: "Base.Bag_NormalHikingBag", name: "Hiking Backpack", category: "Backpacks" },
  { id: "Base.Bag_BigHikingBag", name: "Big Hiking Backpack", category: "Backpacks" },
  { id: "Base.Bag_DuffelBag", name: "Duffel Bag", category: "Backpacks" },
  { id: "Base.Bag_Satchel_Leather", name: "Leather Satchel", category: "Backpacks" },
  { id: "Base.Bag_CrudeLeatherBag", name: "Small Leather Backpack", category: "Backpacks" },
  { id: "Base.Bag_FannyPackFront", name: "Fanny Pack", category: "Backpacks" },
  { id: "Base.Purse", name: "Purse", category: "Backpacks" },
  { id: "Base.Bag_HydrationBackpack", name: "Hydration Pack", category: "Backpacks" },
  { id: "Base.Bag_RifleCase1", name: "Gun Case", category: "Backpacks" },
  { id: "Base.PistolCase1", name: "Handgun Case", category: "Backpacks" },
  { id: "Base.Bag_ProtectiveCaseBulkyMilitary", name: "Bulky Military Container", category: "Backpacks" },
  { id: "Base.Toolbox", name: "Toolbox", category: "Backpacks" },
  { id: "Base.FirstAidKit_New", name: "First Aid Kit (Container)", category: "Backpacks" },

  // --- Miscellaneous ---
  { id: "Base.IDcard", name: "ID Card", category: "Miscellaneous" },
  { id: "Base.KeyRing", name: "Key Ring", category: "Miscellaneous" },
  { id: "Base.UmbrellaBlack", name: "Umbrella", category: "Miscellaneous" },
  { id: "Base.Camera", name: "Camera", category: "Miscellaneous" },
  { id: "Base.Necklace_Gold", name: "Gold Necklace", category: "Miscellaneous" },
  { id: "Base.CarKey", name: "Vehicle Key", category: "Miscellaneous" },
  { id: "Base.RadioBlack", name: "ValuTech Radio", category: "Miscellaneous" },
  { id: "Base.HamRadio1", name: "Premium Technologies Ham Radio", category: "Miscellaneous" },
  { id: "Base.Wallet", name: "Wallet", category: "Miscellaneous" },
  { id: "Base.Handbag", name: "Handbag", category: "Miscellaneous" },
  { id: "Base.Cashbox", name: "Cashbox", category: "Miscellaneous" },
  { id: "Base.Suitcase", name: "Suitcase", category: "Miscellaneous" },
];
